# -*- coding: utf-8 -*-
"""defaults_config

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12oOG45u0M-B2KuIjcupbTt_pxuJIFj1Y
"""

seq_len = 16
n_context = 1


def set_parameters(args):
    params_dict = vars(args)
    global seq_len
    global n_context
    if 'seq_len' in params_dict:
        seq_len = params_dict['seq_len']

    if 'n_context' in params_dict:
        n_context = params_dict['n_context']