# -*- coding: utf-8 -*-
"""suma.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qkpDV4VfqNLazoJKQEP2-_6sPectP3LK
"""

def suma(a,b):
  c=a+b
  return c